version: "3.7"

services:
  app:
    build: docker/app
    working_dir: /usr/src/app
    environment:
      - API_KEY=6tToKq52dmvAIEPD1H4uToE9MxaAtJyg
      - GOOGLE_API_KEY=AIzaSyCZwqCpR-sKkVJtbts-quNqpOTWg_QGQrI
    volumes:
      - .:/usr/src/app
    ports:
      - "80:80"
    depends_on:
    - db
  db:
    image: mongo
    environment:
      MONGO_INITDB_DATABASE: speed-dash
    volumes:
      - ./docker/db:/docker-entrypoint-initdb.d
    ports:
      - "27017:27017"